title: Personal Website
logo: /My_Picture/Pic.png
description: B.Sc. - EE - Sharif University of Technology - email: MahdiBabaeiee@gmail.com
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - projects.md
  - contact.md




