title: Mahdi Babaei
logo: /My_Picture/Pic.png
description: B.Sc. - EE - Sharif University of Technology
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - projects.md
  - RCTP.md
  - SourceReconstruction.md
  - UBCDenoisingPipeline.md
  - IPMNDASS.md
  - CircuitProject.md
  - fMRIProject.md
  - CAProject.md
  - SVMProject.md

